config/routes.rb
Rails.application.routes.draw do  
  resources :topics, only: [:index, :show]
  devise_for :users, path:'', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'	
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
	<div class="inner">
	  <p class="app-footer"><%= copyright_generator %></p>
	</div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h2 class="masthead-brand">L. Sanjaya Ranaweera</h2>
    <nav class="nav nav-masthead app-nav ">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
	<div class="inner">
	  <p><%= copyright_generator %></p>
	</div>
	<p>
	  <a href="#">Back to top</a>
	</p>
</footer>
   

app/views/shared/_blog_header.html.erb
<header class="blog-header py-3">
  <div class="container">
    <h1 class="blog-post-title">My Blog</h1>
    <p class="blog-post-meta">An example blog built with Bootstrap </p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)%>
    </span>
    <span>
      <%= link_to 'Topics', topics_path %>
    </span>    
  </div>      
</header>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded nav-masthead">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
  	<%= link_to "L. Sanjaya Ranaweera", root_path, class: 'navbar-brand' %>
  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
  	  <ul class="navbar-nav mr-auto">
  	  	<%= nav_helper "nav-link", "li" %>
    	<%= login_helper "nav-link" %>
  	  </ul>
  	</div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">You can find <em>Sanjaya's Portfolio</em> in the following social media links.</p>
  </div>

  <%= source_helper("alert alert-primary blog-sidebar-source") %>

  <div class="p-4">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
</aside> 

app/views/shared/_nav.html.erb
<div class="<%= location %>">
      <%= link_to "Home", root_path %>
      <%= link_to "About", about_me_path %>
      <%= link_to "Contact", contact_path %>
      <%= link_to "Blogs", blogs_path %>
      <%= link_to "Portfolios", portfolios_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <footer class="mastfoot mt-auto">
		<p class="float-right">
          <%= link_to "View all Portfolio Items", portfolios_path %> /
	      <a href="#">Back to top</a>
	    </p>    	
		<p class="inner">
		  <%= copyright_generator %>
		</p>
	</footer>  
  </div>
</footer>i

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
	<div class="container">
	  <h1>My Portfolio</h1>
	  <p class="lead text-muted">Here are a collection of Programing languages that I'm currently working on.</p>
	  <p>
	  	<%= link_to "Find out more About me", about_me_path, class: "btn btn-primary my-2"%>
	  	<%= link_to "My current Blogs", blogs_path, class: "btn btn-secondary my-2"%>
	  </p>
	</div>
</section>
 

app/views/shared/_portfolio_nav.html.erb
<header>                                                      
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">I'm a Ruby on Rails Developer with over eighteen months of programming experience.</p>
          <p class="text-muted">For this reason I decided to utilize a completely different development that focus highly on communication and transparent design pattern. When I take up on a project not only do I work to craft the application according to the clients specifications I give daily updates to ensure that the project is aligning properly with the client’s goals. The end result is the right product, delivered on time and on budget.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper "text-white", "li" %>
            <li><%= login_helper "text-white" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>L. Sanjaya Ranaweera</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

      